bot:
  access_control:
    groups:
      - group:
          id: -1001150551096
          url: t.me/devopsitalia
          crosspost_tags:
            - devops
          admin:
            ids:
              - 131000337  # @mmat11
              - 43120899   # @mirioo
            permissions:
              - ban
              - unban
          #moderator:
          #  ids:
          #    - 1234
          #  permissions:
          #    - unban
      - group:
          id: -1001476422781
          url: t.me/kubernetes_it
          crosspost_tags:
            - kubernetes
            - k8s
          admin:
            ids:
              - 797091005  # @pr0metherion
            permissions:
              - ban
              - unban
      - group:
          id: -1001141557431
          url: t.me/golangita
          crosspost_tags:
            - golang
          admin:
            ids:
              - 40323575  # @lucacavallaro
            permissions:
              - ban
              - unban
      - group:
          id: -1001271237061
          url: t.me/kafkastreaming
          crosspost_tags:
            - kafka
          admin:
            ids:
              - 82046673  # @ugolandini
            permissions:
              - ban
              - unban
