bot:
  database:
    type: badger  # alternatives: inmemory
  access_control:
    mods:
      ids:
        - 131000337  # @mmat11
        - 43120899   # @mirioo
        - 797091005  # @pr0metherion
        - 40323575   # @lucacavallaro
        - 82046673   # @ugolandini
        - 647357073  # @sakulsuvarn
        - 14927163   # @enrico204
        - 347743167  # @albus983
    groups:
      - group:
          id: -1001150551096
          url: t.me/devopsitalia
          crosspost_tags:
            - devops
            - ops
          admin:
            ids:
              - 131000337  # @mmat11
              - 43120899   # @mirioo
            permissions:
              - ban
              - unban
              - broadcast
      - group:
          id: -1001476422781
          url: t.me/kubernetes_it
          crosspost_tags:
            - kubernetes
            - k8s
          admin:
            ids:
              - 797091005  # @pr0metherion
              - 131000337  # @mmat11
            permissions:
              - ban
              - unban
              - broadcast
      - group:
          id: -1001141557431
          url: t.me/golangita
          crosspost_tags:
            - go
            - golang
          admin:
            ids:
              - 40323575   # @lucacavallaro
            permissions:
              - ban
              - unban
              - broadcast
      - group:
          id: -1001271237061
          url: t.me/kafkastreaming
          welcome_message: '👋 e benvenuto, cosa fai di bello con kafka/nats/pulsar/streaming vari?'
          crosspost_tags:
            - kafka
          admin:
            ids:
              - 82046673   # @ugolandini
              - 647357073  # @sakulsuvarn
            permissions:
              - ban
              - unban
              - broadcast
      - group:
          id: -1001329456697
          url: t.me/Sistemisti_Italiani
          crosspost_tags:
            - sys
            - ops
          admin:
            ids:
              - 14927163   # @enrico204
              - 347743167  # @albus983
            permissions:
              - ban
              - unban
              - broadcast
      - group:
          id: -1001419379378
          url: t.me/vienialbar
          crosspost_tags:
            - ot
            - offtopic
          admin:
            ids:
              - 131000337  # @mmat11
              - 43120899   # @mirioo
              - 797091005  # @pr0metherion
              - 40323575   # @lucacavallaro
              - 82046673   # @ugolandini
              - 647357073  # @sakulsuvarn
              - 14927163   # @enrico204
              - 347743167  # @albus983
            permissions:
              - ban
              - unban
              - broadcast
  tasks:
    - task:
        name: StoreCleanup
        cron: '@every 15m'
        args:
          - arg:
              name: retention
              value: 604800  # 1 week
    - task:
        name: WelcomeMessage
        cron: '05 8,12,16,20 * * *'
        args:
          - arg:
              name: kubernetesITCfg
              value: |
                group_id: -1001476422781
                message_template_single: '👋 e benvenuto {{.NewUsers}}. Cosa fai di bello con k8s?'
                message_template_multiple: '👋 e benvenuti {{.NewUsers}}. Cosa fate di bello con k8s?'
          - arg:
              name: devopsITCfg
              value: |
                group_id: -1001150551096
                message_template_single: 'Benvenuto {{.NewUsers}}!'
                message_template_multiple: 'Benvenuti {{.NewUsers}}!'
          - arg:
              name: barettoCfg
              value: |
                group_id: -1001419379378
                message_template_single: 'Ciao {{.NewUsers}}. ☕?'
                message_template_multiple: 'Ciao {{.NewUsers}}. ☕?'
