bot:
  access_control:
    groups:
      - group:
          id: -1001150551096
          url: t.me/devopsitalia
          crosspost_tags:
            - devops
          admin:
            ids:
              - 131000337  # @mmat11
              - 43120899   # @mirioo
            permissions:
              - ban
              - unban
              - broadcast
          moderator:
            ids:
              - 797091005  # @pr0metherion
              - 40323575   # @lucacavallaro
              - 82046673   # @ugolandini
      - group:
          id: -1001476422781
          url: t.me/kubernetes_it
          crosspost_tags:
            - kubernetes
            - k8s
          admin:
            ids:
              - 797091005  # @pr0metherion
            permissions:
              - ban
              - unban
              - broadcast
          moderator:
            ids:
              - 131000337  # @mmat11
              - 43120899   # @mirioo
              - 40323575   # @lucacavallaro
              - 82046673   # @ugolandini
      - group:
          id: -1001141557431
          url: t.me/golangita
          crosspost_tags:
            - go
            - golang
          admin:
            ids:
              - 40323575  # @lucacavallaro
            permissions:
              - ban
              - unban
              - broadcast
          moderator:
            ids:
              - 131000337  # @mmat11
              - 43120899   # @mirioo
              - 797091005  # @pr0metherion
              - 82046673   # @ugolandini
      - group:
          id: -1001271237061
          url: t.me/kafkastreaming
          welcome_message: '👋 e benvenuto, cosa fai di bello con kafka/nats/pulsar/streaming vari?'
          crosspost_tags:
            - kafka
          admin:
            ids:
              - 82046673  # @ugolandini
            permissions:
              - ban
              - unban
              - broadcast
          moderator:
            ids:
              - 131000337  # @mmat11
              - 43120899   # @mirioo
              - 797091005  # @pr0metherion
              - 40323575   # @lucacavallaro
  tasks:
    - task:
        name: StoreCleanup
        cron: '@every 5m'
        args:
          - arg:
              name: retention
              value: 86400  # 24h
    - task:
        name: WelcomeMessage
        cron: '05 8,12,16,20 * * *'
        args:
          - arg:
              name: kubernetesITCfg
              value: |
                group_id: -1001476422781
                message_template_single: '👋 e benvenuto {{.NewUsers}}. Cosa fai di bello con k8s?'
                message_template_multiple: '👋 e benvenuti {{.NewUsers}}. Cosa fate di bello con k8s?'
          - arg:
              name: devopsITCfg
              value: |
                group_id: -1001150551096
                message_template_single: 'Benvenuto {{.NewUsers}}!'
                message_template_multiple: 'Benvenuti {{.NewUsers}}!'
